name: BattleRoyale
version: 1.0
api: 3.0.0
author: PiyushBest, Many1337 (Fixer)
website: https://github.com/PiyushBest
description: Minijuego para PocketMine-MP/Altay
main: BattleRoyale\GameManager
